"""create initial storage schema

Revision ID: e3889a51ba5a
Revises:
Create Date: 2026-08-29 18:53:55.650681

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e3889a51ba5a"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "storage_nodes",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("node_id", sa.String(length=128), nullable=False),
        sa.Column("endpoint", sa.String(length=512), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("capacity_bytes", sa.BigInteger(), nullable=False),
        sa.Column("used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("last_heartbeat", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_storage_nodes_node_id"),
        "storage_nodes",
        ["node_id"],
        unique=True,
    )

    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("quota_bytes", sa.BigInteger(), nullable=False),
        sa.Column("used_bytes", sa.BigInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_email"),
        "users",
        ["email"],
        unique=True,
    )

    op.create_table(
        "audit_logs",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("resource_type", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=128), nullable=True),
        sa.Column("details", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_logs_action"),
        "audit_logs",
        ["action"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_created_at"),
        "audit_logs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_user_id"),
        "audit_logs",
        ["user_id"],
        unique=False,
    )

    op.create_table(
        "files",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("current_version_id", sa.BigInteger(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_files_owner_id"),
        "files",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        "ix_files_owner_name",
        "files",
        ["owner_id", "name"],
        unique=False,
    )

    op.create_table(
        "file_versions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("version_number", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "file_id",
            "version_number",
            name="uq_file_versions_file_version",
        ),
    )
    op.create_index(
        op.f("ix_file_versions_checksum"),
        "file_versions",
        ["checksum"],
        unique=False,
    )
    op.create_index(
        "ix_file_versions_file_created",
        "file_versions",
        ["file_id", "created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_file_versions_file_id"),
        "file_versions",
        ["file_id"],
        unique=False,
    )

    op.create_table(
        "shares",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("permission", sa.String(length=32), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_shares_file_id"),
        "shares",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shares_owner_id"),
        "shares",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_shares_token_hash"),
        "shares",
        ["token_hash"],
        unique=True,
    )

    op.create_table(
        "upload_sessions",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=False),
        sa.Column("file_id", sa.BigInteger(), nullable=True),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("mime_type", sa.String(length=255), nullable=True),
        sa.Column("total_size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("chunk_size_bytes", sa.Integer(), nullable=False),
        sa.Column("total_chunks", sa.Integer(), nullable=False),
        sa.Column("received_chunks", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_upload_sessions_expires",
        "upload_sessions",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_upload_sessions_file_id"),
        "upload_sessions",
        ["file_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_upload_sessions_owner_id"),
        "upload_sessions",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        "ix_upload_sessions_owner_status",
        "upload_sessions",
        ["owner_id", "status"],
        unique=False,
    )

    op.create_table(
        "chunks",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("version_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_number", sa.Integer(), nullable=False),
        sa.Column("size_bytes", sa.BigInteger(), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.ForeignKeyConstraint(
            ["version_id"],
            ["file_versions.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "version_id",
            "chunk_number",
            name="uq_chunks_version_number",
        ),
    )
    op.create_index(
        "ix_chunks_content_hash",
        "chunks",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chunks_version_id"),
        "chunks",
        ["version_id"],
        unique=False,
    )

    op.create_table(
        "chunk_replicas",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_id", sa.BigInteger(), nullable=False),
        sa.Column("storage_node_id", sa.BigInteger(), nullable=False),
        sa.Column("storage_key", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("checksum", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["chunks.id"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["storage_node_id"],
            ["storage_nodes.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "chunk_id",
            "storage_node_id",
            name="uq_chunk_replicas_chunk_node",
        ),
    )
    op.create_index(
        op.f("ix_chunk_replicas_chunk_id"),
        "chunk_replicas",
        ["chunk_id"],
        unique=False,
    )
    op.create_index(
        "ix_chunk_replicas_status",
        "chunk_replicas",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_chunk_replicas_storage_node_id"),
        "chunk_replicas",
        ["storage_node_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_chunk_replicas_storage_node_id"),
        table_name="chunk_replicas",
    )
    op.drop_index(
        "ix_chunk_replicas_status",
        table_name="chunk_replicas",
    )
    op.drop_index(
        op.f("ix_chunk_replicas_chunk_id"),
        table_name="chunk_replicas",
    )
    op.drop_table("chunk_replicas")

    op.drop_index(
        op.f("ix_chunks_version_id"),
        table_name="chunks",
    )
    op.drop_index(
        "ix_chunks_content_hash",
        table_name="chunks",
    )
    op.drop_table("chunks")

    op.drop_index(
        "ix_upload_sessions_owner_status",
        table_name="upload_sessions",
    )
    op.drop_index(
        op.f("ix_upload_sessions_owner_id"),
        table_name="upload_sessions",
    )
    op.drop_index(
        op.f("ix_upload_sessions_file_id"),
        table_name="upload_sessions",
    )
    op.drop_index(
        "ix_upload_sessions_expires",
        table_name="upload_sessions",
    )
    op.drop_table("upload_sessions")

    op.drop_index(
        op.f("ix_shares_token_hash"),
        table_name="shares",
    )
    op.drop_index(
        op.f("ix_shares_owner_id"),
        table_name="shares",
    )
    op.drop_index(
        op.f("ix_shares_file_id"),
        table_name="shares",
    )
    op.drop_table("shares")

    op.drop_index(
        op.f("ix_file_versions_file_id"),
        table_name="file_versions",
    )
    op.drop_index(
        "ix_file_versions_file_created",
        table_name="file_versions",
    )
    op.drop_index(
        op.f("ix_file_versions_checksum"),
        table_name="file_versions",
    )
    op.drop_table("file_versions")

    op.drop_index(
        "ix_files_owner_name",
        table_name="files",
    )
    op.drop_index(
        op.f("ix_files_owner_id"),
        table_name="files",
    )
    op.drop_table("files")

    op.drop_index(
        op.f("ix_audit_logs_user_id"),
        table_name="audit_logs",
    )
    op.drop_index(
        op.f("ix_audit_logs_created_at"),
        table_name="audit_logs",
    )
    op.drop_index(
        op.f("ix_audit_logs_action"),
        table_name="audit_logs",
    )
    op.drop_table("audit_logs")

    op.drop_index(
        op.f("ix_users_email"),
        table_name="users",
    )
    op.drop_table("users")

    op.drop_index(
        op.f("ix_storage_nodes_node_id"),
        table_name="storage_nodes",
    )
    op.drop_table("storage_nodes")
    # ### end Alembic commands ###